### ISSUE TITLE
últimas pendências do boletim

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/boletim#4]
- Na tabela que lista os FFLCh na mídia mostrar uma coluna com o ome do veículo
- Opção de enviar para um email email de teste
- Configurar envio para as 7 listas atuais
- Mensagem de confirmação ao enviar boletim por email
- Depois que enviado, não deixar o botão de enviar novamente

**Comment by ricardfo** [comment]
Resolvido no último pull-request
